modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/utility-belt/issues"

[[mods]]
modId = "utility_belt"
version = "${file.jarVersion}"
displayName = "Utility Belt"
displayURL="https://github.com/JamCoreModding/utility-belt"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Free your hotbar
'''

[[dependencies.utility_belt]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.utility_belt]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.utility_belt]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.utility_belt]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.utility_belt]]
modId = "accessories"
type = "required"
versionRange = "[${accessories_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "utility_belt.mixins.json"

[[mixins]]
config = "utility_belt.client.mixins.json"
