#!/bin/bash

platform=$1
output_file=$(mktemp)
./gradlew $platform:runServer > "$output_file" 2>&1 &
command_pid=$!
sleep 60

if ps -p $command_pid > /dev/null; then
  echo "Command still running, assuming it was a success and killing it..."
  kill -9 $command_pid
  cat "$output_file"
  rm "$output_file"
  exit 0
else
  echo "Command finished within time limit, considering it to be a failure..."
  cat "$output_file"
  rm "$output_file"
  exit 1
fi
